config/routes.rb
Rails.application.routes.draw do
  root "schools#index"

  resources :schools do
    resources :students
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/school.rb
class School < ApplicationRecord
  has_many :students, dependent: :destroy
end

app/models/student.rb
class Student < ApplicationRecord
  belongs_to :school
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController
  def index
    @schools = School.all
    @students = Student.all

    @prize_schools = Student.where("place <= 3")
    @most_successful_school = Student.where("place <= 3").
      group(:school).limit(5)
    @winners = Student.where("place = 1")
  end

  def show
    @school = School.find(params[:id])
  end

  def new
    @school = School.new
  end

  def create
    @school = School.new(school_params)

    if @school.save
      redirect_to @school
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @school = School.find(params[:id])
  end

  def update
    @school = School.find(params[:id])

    if @school.update(school_params)
      redirect_to @school
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @school = School.find(params[:id])
    @school.destroy

    redirect_to root_path, status: :see_other
  end

  private
  def school_params
    params.require(:school).permit(:number, :address)
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  def create
    @school = School.find(params[:school_id])
    @student = @school.students.create(student_params)
    redirect_to school_path(@school)
  end

  def edit
    @school = School.find(params[:school_id])
    @student = Student.find(params[:id])
  end

  def update
    @student = Student.find(params[:id])

    if @student.update(student_params)
      redirect_to root_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @student = Student.find(params[:id])
    @student.destroy
    redirect_to root_path
  end

  private
  def student_params
    params.require(:student).permit(:surname, :grade, :place)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProjectRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/schools/_form.html.erb
<%= form_with model: school do |form| %>
  <div>
    <%= form.label :number %><br>
    <%= form.text_field :number %>
    <% school.errors.full_messages_for(:number).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :address %><br>
    <%= form.text_field :address %><br>
    <% school.errors.full_messages_for(:address).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/schools/edit.html.erb
<h1>Edit School</h1>

<%= render "form", school: @school %>

app/views/schools/index.html.erb
<h1>Schools</h1>

<ul>
  <% @schools.each do |school| %>
    <li>
      <a href="<%= school_path(school) %>">
        <%= school.number %>
      </a>
    </li>
  <% end %>
</ul>

<%= link_to "Add School", new_school_path %>

<table>
  <tr>
    <th>Surname</th>
    <th>School</th>
    <th>Grade</th>
    <th>Place</th>

  </tr>
  <% @students.each do |student|  %>
    <tr>
      <th><%= student.surname%></th>
      <th><%= student.school.number%></th>
      <th><%= student.grade%></th>
      <th><%= student.place%></th>
    </tr>
  <% end %>
</table>

<h3>Schools with prize places</h3>
<table>
  <% @prize_schools.each do |student| %>
    <tr>
      <th><%= student.school.number %></th>
    </tr>
  <% end %>
</table>

<h3>Most successful schools</h3>
<table>
  <tr>
    <th>School</th>
  </tr>
  <% @most_successful_school.each do |student| %>
    <tr>
      <th><%= student.school.number %></th>
    </tr>
  <% end %>
</table>

<h3>First place winners</h3>
<table>
  <tr>
    <th>Surname</th>
    <th>School</th>
    <th>Grade</th>
  </tr>
  <% @winners.each do |student| %>
    <tr>
      <th><%= student.surname %></th>
      <th><%= student.school.number %></th>
      <th><%= student.grade %></th>
    </tr>
  <% end %>
</table>

app/views/schools/new.html.erb
<h1>New School</h1>

<%= render "form", school: @school %>

app/views/schools/show.html.erb
<p><%= @school.number %></p>

<p><%= @school.address %></p>

<ul>
  <li><%= link_to "Edit", edit_school_path(@school) %></li>
  <li><%= link_to "Destroy",school_path(@school), data: {
    turbo_method: :delete,
    turbo_confirm: "Are you sure?"
  } %></li>
</ul>

<h2>Students</h2>
<% @school.students.each do |student| %>
  <p>
    <strong>Surname:</strong>
    <%= student.surname %>
  </p>

  <p>
    <strong>grade:</strong>
    <%= student.grade %>
  </p>

  <p>
    <strong>place:</strong>
    <%= student.place %>
  </p>

  <p>
    <%= link_to "Delete Student", [student.school, student], data: {
      turbo_method: :delete,
      turbo_confirm: "Are you sure?"
    } %>
  </p>
<% end %>


<h2>Add a student:</h2>
<%= form_with model: [ @school, @school.students.build ] do |form| %>
  <p>
    <%= form.label :surname %><br>
    <%= form.text_field :surname %>
  </p>

  <p>
    <%= form.label :grade %><br>
    <%= form.select :grade, [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11], selected: 1 %><br>
  </p>

  <p>
    <%= form.label :place %><br>
    <%= form.select :place, [1, 2, 3], selected: 1%><br>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/students/_form.html.erb
<%= form_with model: student do |form| %>
  <div>
    <%= form.label :surname %><br>
    <%= form.text_field :surname %>
    <% student.errors.full_messages_for(:surname).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :school %><br>
    <%= select_tag 'school_number', options_for_select(@schools.collect { |school| [school.number]}), class: "form-control" %><br>
    <% student.errors.full_messages_for(:school).each do |message| %>
      <div><%= message %></div>Sc
    <% end %>
  </div>

  <div>
    <%= form.label :grade %><br>
    <%= form.select :grade, [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11], selected: 1 %><br>
  </div>

  <div>
    <%= form.label :place %><br>
    <%= form.select :place, [1, 2, 3], selected: 1%><br>
  </div>

  <div>
    <button class="btn"><%= form.submit %></button>
  </div>
<% end %>

app/views/students/edit.html.erb
<%= form_with model: [ @school, @school.students.edit ] do |form| %>
  <p>
    <%= form.label :surname %><br>
    <%= form.text_field :student.surname %>
  </p>

  <p>
    <%= form.label :grade %><br>
    <%= form.select :grade, [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11], selected: student.grade %><br>
  </p>

  <p>
    <%= form.label :place %><br>
    <%= form.select :place, [1, 2, 3], selected: student.place%><br>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>